name: Check Asset updates

on:
  pull_request:
    paths:
      - 'assets.json'
      - 'assets.gen.json'

jobs:
  check_generated_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python requirements
        run: pip install -r requirements.txt

      - name: Regenerate asset JSON and markdown
        run: |
          python create_assets_json.py
          python create_assets_md.py

      - name: Check if assets.gen.json is up-to-date
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          if git diff --exit-code assets.gen.json; then
            echo "assets.gen.json is up-to-date."
          else
            echo "assets.gen.json is not up-to-date with assets.json."
            echo "Please run create_assets_json.py and commit the changes to assets.gen.json."
            exit 1
          fi

      - name: Check if ASSETS.md is up-to-date
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          if git diff --exit-code ASSETS.md; then
            echo "ASSETS.md is up-to-date."
          else
            echo "ASSETS.md is not up-to-date with assets.json."
            echo "Please run create_assets_md.py and commit the changes to ASSETS.md."
            exit 1
          fi
